### ISSUE TITLE
Lib missing

### ISSUE THREAD

**Issue by dynamick** [CodyReichert/materializer#1]
Hi Cody,
it seems that the library is missing in this repository.

Could you help me?
Mick

**Comment by CodyReichert** [comment]
Hey @dynamick 

I originally didn't plan on releasing the plugin. But I never ended up using it for anything else, so what the heck - the code is pushed.

Note two things:
- The JS dependencies need to be compiled before everything will work (in a bash shell: `npm run build-all`. On a different OS, just look at the webpack command in `package.json`).
- I haven't used it in a while so if you have any problems feel free to open another issue.

Enjoy :)

**Comment by CodyReichert** [comment]
Oh, there is also a zip file that you should be able install in your dashboard: https://github.com/CodyReichert/materializer/releases/tag/v0.0.1

**Comment by dynamick** [comment]
Great Cody! Thanks for sharing your work!
