### ISSUE TITLE
nav issue

### ISSUE THREAD

**Issue by sharkt** [CodyReichert/materializer#2]
Hi, 
Your work is amazing and so easy to use! Thumbs up man! I got one issue whit the nav section it get a double nav section. See the screenshot!
![screen_shot](https://cloud.githubusercontent.com/assets/11199063/10832422/fc751d4c-7e50-11e5-9b34-d90a14e4b577.png)

I'm using the listify theme (http://themeforest.net/item/wordpress-directory-theme-listify/9602611)

Thanks!

**Comment by CodyReichert** [comment]
Hey @sharkt, thanks for the report.

Just to clarify - are you using any short-codes on that page, or does that happen right after activating the plugin?

And last thing - which part of the nav is actually doubled? The grey part (like below)?
![materializer-screenshot](https://cloud.githubusercontent.com/assets/7034627/10838423/d813e724-7e93-11e5-944b-1d24f3ca9f5a.png)

**Comment by sharkt** [comment]
Hi,
Thanks for the fast reply !!!! ;)
Yes it happen right after the plugin activation... If off the the menu layout properly. And yes it's the grey part of it that is bad, not suppose to be there!
I could provide access to the wp install. Did you propose any theme better then other one to work whit your plugin?
Thanks

**Comment by CodyReichert** [comment]
Hi @sharkt,

This is fixed in the latest release (v0.2.0). It's published to WordPress so you can download it from there or here.

Please re-open if there are any more issues. Thanks again!

**Comment by sharkt** [comment]
That's fix thanks man! Just did a 5 stars review on WP.org site!

**Comment by CodyReichert** [comment]
Not a problem, and thanks a ton - that's awesome!
