### ISSUE TITLE
Collapsibles popout

### ISSUE THREAD

**Issue by grampa** [CodyReichert/materializer#5]
HI, 
how to make collapsibles popout effect?

**Comment by CodyReichert** [comment]
Is this what you're looking for? http://codyreichert.github.io/materializer/#collapsibles

**Comment by grampa** [comment]
Yep, I followed the instructions, but isn't popout disabled by deafult? Do I need do add attribute for popout?

**Comment by CodyReichert** [comment]
Hey, @grampa. Thanks again for the report. I did a bit of investigating so you can get the popout effect working. It looks like the documentation is incorrect. I'll get that fixed up, but you can get the effect working by adding `style="popout"` to the `[collapsible]` short-code. For example:

```
[collapsible style="popout"]
    [collapsible_item title="Item One"]Some content in here.[/collapsible_item]
    [collapsible_item title="Item Two"]Some more content in here.[/collapsible_item]
    [collapsible_item title="Item Three"]And some more content in this guy.[/collapsible_item]
[/collapsible]
```

**Comment by grampa** [comment]
It works now. Thanks.

**Comment by CodyReichert** [comment]
Great, thanks for letting me know @grampa!
